# This is a configuration file for the bacon tool
#
# Bacon repository: https://github.com/Canop/bacon
# Complete help on configuration: https://dystroy.org/bacon/config/
# You can also check bacon's own bacon.toml file
#  as an example: https://github.com/Canop/bacon/blob/main/bacon.toml

default_job = "build"

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.build]
command = [
  "wasm-pack", "build",
  "--target", "web", "--out-name", "workflow-terminal",
  "--out-dir", "root/workflow-terminal"
]
need_stdout = true
allow_warnings = true

[jobs.hack]
command = [
  "wasm-pack", "build",
  "--target", "web", "--out-name", "workflow-terminal",
  "--out-dir", "root/workflow-terminal",
  "--features", "hacking", "--no-default-features"
]
need_stdout = true
allow_warnings = true

# You may define here keybindings that would be specific to
# a project, for example a shortcut to launch a specific job.
# Shortcuts to internal functions (scrolling, toggling, etc.)
# should go in your personal global prefs.toml file instead.
[keybindings]
b = "job:build"
h = "job:hack"

